const categories={Schule:['#2f6fed','#eaf1ff'],Lernen:['#14a673','#e8f8f2'],Nachhilfe:['#8250df','#f2edff'],Cup:['#e5484d','#ffeded'],'Scrims/Practice':['#f59e0b','#fff5dc'],Gym:['#0891b2','#e6f7fb'],Arbeit:['#667085','#eef0f3'],Sonstiges:['#db5f9a','#fff0f7']};
const school=[['Montag','07:50','16:15','immer 0. Stunde'],['Dienstag','08:45','14:35',''],['Mittwoch','08:45','16:15',''],['Donnerstag','08:45','14:35',''],['Freitag','08:45','14:35','']];
const defaults={events:[{id:'e1',date:'2026-09-18',start:'19:00',end:'22:00',name:'Trio Skin Cup',category:'Cup'},{id:'e2',date:'2026-09-16',start:'19:00',end:'23:00',name:'Aushelfen Freund',category:'Sonstiges'}],tasks:[{id:'t1',date:'2026-09-18',subject:'Mathe',text:'Test: exponentielles Wachstum, lineare Funktionen / Parametereinfluss',done:false},{id:'t2',date:'2026-09-18',subject:'Englisch',text:'Vokabeltest – ca. 30 Vokabeln',done:false}]};
const key='emilios-weekplan-v1';let data=JSON.parse(localStorage.getItem(key)||'null')||structuredClone(defaults);let weekStart=startOfWeek(new Date());
const fmtDate=new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit'}),fmtLong=new Intl.DateTimeFormat('de-DE',{day:'numeric',month:'long'}),days=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'];
function localDate(d){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}function save(){localStorage.setItem(key,JSON.stringify(data));render()}function schoolEntry(i,date){if(i>4)return null;return{name:'Schule',start:school[i][1],end:school[i][2],category:'Schule',date}}
function render(){renderSummary();renderWeek();renderTasks();}
function renderSummary(){const now=new Date(),future=data.events.map(e=>({...e,at:new Date(`${e.date}T${e.start}`)})).filter(e=>e.at>=now).sort((a,b)=>a.at-b.at)[0];document.querySelector('#next-event').textContent=future?.name||'Keine Termine';document.querySelector('#next-event-time').textContent=future?`${fmtLong.format(future.at)} · ${future.start}`:'Du hast gerade Luft';const open=data.tasks.filter(t=>!t.done&&new Date(t.date+'T23:59')>=now).length;document.querySelector('#open-count').textContent=open;document.querySelector('#open-label').textContent=open===1?'eine Sache offen':open?'Sachen offen':'Alles erledigt';const mins=school.reduce((n,s)=>{const [sh,sm]=s[1].split(':').map(Number),[eh,em]=s[2].split(':').map(Number);return n+(eh*60+em-sh*60-sm)},0);document.querySelector('#school-hours').textContent=`${Math.floor(mins/60)} h ${mins%60||''}`.trim()}
function renderWeek(){const end=addDays(weekStart,6);document.querySelector('#week-label').textContent=`${fmtLong.format(weekStart)} – ${fmtLong.format(end)}`;document.querySelector('#legend').innerHTML=Object.entries(categories).map(([n,c])=>`<span style="--chip:${c[1]};--chip-ink:${c[0]}">${n}</span>`).join('');document.querySelector('#week-grid').innerHTML=days.map((name,i)=>{const date=addDays(weekStart,i),iso=localDate(date),items=[schoolEntry(i,iso),...data.events.filter(e=>e.date===iso),...data.tasks.filter(t=>t.date===iso&&!t.done).map(t=>({name:`${t.subject}: ${t.text}`,start:'Aufgabe',end:'',category:'Lernen',task:true}))].filter(Boolean).sort((a,b)=>a.start.localeCompare(b.start));return `<article class="day ${iso===localDate(new Date())?'today':''}"><div class="day-head"><span class="day-name">${name}</span><span class="day-date">${fmtDate.format(date)}</span></div>${items.map(e=>`<div class="entry ${e.category==='Schule'?'school':''} ${e.task?'task':''}" style="--entry:${categories[e.category]?.[0]||categories.Sonstiges[0]}"><strong>${escapeHtml(e.name)}</strong><small>${e.start}${e.end?'–'+e.end:''}</small></div>`).join('')||'<div class="empty">Frei</div>'}</article>`}).join('')}
function renderTasks(){const list=[...data.tasks].sort((a,b)=>a.done-b.done||a.date.localeCompare(b.date));document.querySelector('#task-list').innerHTML=list.length?list.map(t=>`<label class="task-row ${t.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span><strong>${escapeHtml(t.subject)}</strong><small>${escapeHtml(t.text)}</small></span><small>${new Date(t.date+'T12:00').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}</small></label>`).join(''):'<div class="empty">Keine Aufgaben eingetragen</div>';document.querySelector('#school-list').innerHTML=school.map(s=>`<div class="school-row"><span><strong>${s[0]}</strong>${s[3]?' · '+s[3]:''}</span><span>${s[1]}–${s[2]}</span></div>`).join('');document.querySelectorAll('[data-task]').forEach(el=>el.addEventListener('change',()=>{data.tasks.find(t=>t.id===el.dataset.task).done=el.checked;save()}))}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.querySelector('#prev-week').onclick=()=>{weekStart=addDays(weekStart,-7);render()};document.querySelector('#next-week').onclick=()=>{weekStart=addDays(weekStart,7);render()};document.querySelector('#today').onclick=()=>{weekStart=startOfWeek(new Date());render()};
const dialog=document.querySelector('#entry-dialog'),form=document.querySelector('#entry-form'),type=document.querySelector('#entry-type');document.querySelector('#entry-category').innerHTML=Object.keys(categories).filter(x=>x!=='Schule').map(x=>`<option>${x}</option>`).join('');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{type.value=b.dataset.open;const task=type.value==='task';document.querySelector('#dialog-title').textContent=task?'Aufgabe oder Test':'Termin';document.querySelector('#event-fields').hidden=task;document.querySelector('#task-fields').hidden=!task;document.querySelector('#entry-date').value=localDate(new Date());dialog.showModal()});form.addEventListener('submit',e=>{e.preventDefault();const date=document.querySelector('#entry-date').value;if(type.value==='task'){const subject=document.querySelector('#entry-subject').value.trim(),text=document.querySelector('#entry-task').value.trim();if(!subject||!text)return;data.tasks.push({id:crypto.randomUUID(),date,subject,text,done:false})}else{const name=document.querySelector('#entry-name').value.trim();if(!name)return;data.events.push({id:crypto.randomUUID(),date,start:document.querySelector('#entry-start').value,end:document.querySelector('#entry-end').value,name,category:document.querySelector('#entry-category').value})}form.reset();dialog.close();save()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
